### ISSUE TITLE
[Feature Request] Add flag to pass affirmative (--yes/-y?)

### ISSUE THREAD

**Issue by SuperJC710e** [pycampers/eopkg3p#1]
Thanks for this program, it's very useful. Since discovering it I've incorporated it into a post fresh-install installation script. As such it would be really great to have the affirmative option that would also pass that option to eopkg command that installs dependencies. Of course, it is understandable if you don't want pursue adding it with the future depreciation of third party coming.

**Comment by devxpy** [comment]
It's already there in `v0.0.6`!

```
$ eopkg3p install --help
Usage: eopkg3p install [OPTIONS] [PACKAGES]...

  (it) Install packages

Options:
  --reinstall
  -y, --yes    Don't ask for confirmation.
  --help       Show this message and exit.
$ eopkg3p upgrade --help
Usage: eopkg3p upgrade [OPTIONS] [PACKAGES]...

  (up) Upgrade 3rd party packages

Options:
  -y, --yes  Don't ask for confirmation.
  --help     Show this message and exit.
```

**Comment by SuperJC710e** [comment]
Oh, I didn't see that option in the help message of the version pip installed for me. But I do see that this version was released some time ago, so I should have the latest. I'll check into it when I'm back at my system. Thanks again, and please go ahead and close this issue if you wish…oh right, I can do that…Thus Closed!
