### ISSUE TITLE
Python-documentation?

### ISSUE THREAD

**Issue by geirawsm** [pycampers/eopkg3p#2]
Hi,
Any chance of getting documentation on the API?

**Comment by devxpy** [comment]
I'm sorry, but I have switched to mac.

The [python code](https://github.com/pycampers/eopkg3p/blob/master/eopkg3p/core.py) is type annotated though and should be pretty straightforward to figure out.

**Comment by geirawsm** [comment]
Cheers, I might have a look at it and make a PR of some kind.
