### ISSUE TITLE
This broke today after Solus updates (14/2-20)

### ISSUE THREAD

**Issue by henkesteen** [pycampers/eopkg3p#7]
After today's updates, this package is now broken.

The output says:
```/usr/bin/env: ‘python3.6’: No such file or directory```

I really appreciate this software, it would be awesome if it still worked =)

**Comment by devxpy** [comment]
Sorry, I am not on Solus anymore. But feel free to replace `python3.6` with just `python3` [here](https://github.com/scientifichackers/eopkg3p/blob/3514771e6124dbee90abd0ed59841498e69361d7/build.sh#L16), and build the package again :)

I'll do whenever I get my hands on a solus machine.

**Comment by sebastian-brandt** [comment]
Just reinstalled with "sudo pip3 install eopkg3p" and it works again. 
/usr/bin/eopkg3p has #!/usr/bin/python3.7 now.

**Comment by henkesteen** [comment]
Oh nice! thanks!
